# Generated by Django 5.2.3 on 2025-06-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='code',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='input_text',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='output_text',
        ),
        migrations.AddField(
            model_name='submission',
            name='code_file',
            field=models.CharField(default='fileUUID', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='input_file',
            field=models.CharField(default='fileUUID', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='output_file',
            field=models.CharField(default='fileUUID', max_length=40),
            preserve_default=False,
        ),
    ]
