# Generated by Django 5.2.3 on 2025-06-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_submission_code_remove_testcase_input_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code_file',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_file',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output_file',
            field=models.CharField(max_length=60),
        ),
    ]
